--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BlockHorizons/BlockSniper
submodule: true
projects:
  BlockSniper:
    path: ""
    icon: resources/BlockSniperLogo.png
      - src: libschematic/libschematic
        version: ^0.0.6
...
